# Kiểm tra dữ liệu Task 2.2
Notebook này sử dụng Pandas để đọc, kiểm tra schema và phân tích sơ bộ file `Task_2-2.parquet` đã xuất ra từ Hadoop/Spark.

In [11]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [17]:
# Đường dẫn tới file Parquet
file_path = './results/Task_2-2-TP.parquet'

# Đọc file bằng pyarrow hoặc fastparquet
df = pd.read_parquet(file_path)

# Hiển thị 10 dòng đầu tiên
df.tail(10)

,SKU,month,total_orders,p90_threshold_approx,p80_threshold_approx,stddev_amount_p90_approx,stddev_amount_p80_approx,qualifying_orders_p90_approx,qualifying_orders_p80_approx,p90_threshold_exact,p80_threshold_exact,stddev_amount_p90_exact,stddev_amount_p80_exact,qualifying_orders_p90_exact,qualifying_orders_p80_exact
16335,SET444-KR-SH-XXL,2022-06,9,25,24,0.0,27.000000,1,2,25,24,0.0,27.000000,1,2
16336,SET444-KR-SH-XXXL,2022-06,14,26,22,27.0,26.454489,2,5,26,22,27.0,26.454489,2,5
16337,SET445-KR-NP-S,2022-06,1,23,23,0.0,0.000000,1,1,23,23,0.0,0.000000,1,1
16338,SET446-KR-NP-XS,2022-06,1,22,22,0.0,0.000000,1,1,22,22,0.0,0.000000,1,1
16339,SET449-KR-NP-M,2022-06,1,24,24,0.0,0.000000,1,1,24,24,0.0,0.000000,1,1
16340,SET449-KR-NP-S,2022-06,1,25,25,0.0,0.000000,1,1,25,25,0.0,0.000000,1,1
16341,SET461-KR-NP-XL,2022-06,1,1,1,0.0,0.000000,1,1,1,1,0.0,0.000000,1,1
16342,SET461-KR-NP-XS,2022-06,1,1,1,0.0,0.000000,1,1,1,1,0.0,0.000000,1,1
16343,SET461-KR-NP-XXL,2022-06,1,1,1,0.0,0.000000,1,1,1,1,0.0,0.000000,1,1
16344,SET462-KR-NP-S,2022-06,1,24,24,0.0,0.000000,1,1,24,24,0.0,0.000000,1,1

In [13]:
# Xem cấu trúc schema, số lượng dòng và kiểu dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16345 entries, 0 to 16344
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SKU         16345 non-null  object
 1   Month       16345 non-null  int32
 2   count_p80   16345 non-null  int64
 3   stddev_p80  16345 non-null  float64
 4   count_p90   16345 non-null  int64
 5   stddev_p90  16345 non-null  float64
dtypes: float64(2), int32(1), int64(2), object(1)
memory usage: 702.5+ KB

In [14]:
# Kiểm tra tóm tắt thống kê đối với các cột số lượng (đơn hàng & độ lệch chuẩn)
df.describe()

              Month     count_p80    stddev_p80     count_p90    stddev_p90
count  16345.000000  16345.000000  16345.000000  16345.000000  16345.000000
mean       4.959315      2.249128      8.490568      1.960355      6.323591
std        0.837433      3.672199     44.287536      3.299575     36.583812
min        3.000000      1.000000      0.000000      1.000000      0.000000
25%        4.000000      1.000000      0.000000      1.000000      0.000000
50%        5.000000      1.000000      0.000000      1.000000      0.000000
75%        6.000000      2.000000      0.000000      2.000000      0.000000
max        6.000000    178.000000    988.535280    178.000000    753.046967